### ISSUE TITLE
Konečně opendata

### ISSUE THREAD

**Issue by glomerata** [kukosek/czech-covid-db#1]
...jsou ke stažení na:
https://onemocneni-aktualne.mzcr.cz/api/v1/covid-19

**Comment by kukosek** [comment]
Vím o tom. Teď jsem se snažil implementovat na koronagrafy.techbrick.cz aby to stahovalo z tama, jako alternativní zdroj oproti tomuto repozitáři. Vaše issue mě nyní pozastavuje. Takže jestli teda tento repozitář někdo využívá, což mě dost překvapuje, nastává tedy otázka. Chceme, aby to zde fungovalo tak jak doteď (data z wikipedie), nebo zde budeme tahat data z MZČR? S tím že by jsme z nich mohli extrahovat nějaké další data a udělat z nich zvláštní soubory. Například z dat "COVID-19: Přehled osob s prokázanou nákazou dle hlášení krajských hygienických stanic" by se dalo odvozovat, kolik je nakažených v jednotlivých krajích v jednotlivý den, atd.

**Comment by glomerata** [comment]
Nevím. Možná cs.wiki bude též stahovat data z mzcr.cz. Každopádně toho uzis ví hodně ( https://www.uzis.cz/res/file/akce/20200324-covid-19/20200324-dusek.pdf ) a mezi lidi to pouští jen velmi opatrně a po troškách.

**Comment by kukosek** [comment]
Můžu se zeptat, zda, popřípadě jak, používáte tento repozitář a bylo by pro vás lepší kdyby zde byly officiální data z MZČR?

**Comment by kukosek** [comment]
Začal jsem pracovat na novém parseru, který bude brát data z ÚZISu. Předpokládané dokončení: zítra večer

**Comment by kukosek** [comment]
[implementace](https://github.com/kukosek/czech-covid-db-multiparser) je hotová - večer to nahodím do czech-covid-db

**Comment by kukosek** [comment]
Hotovo, už by se to mělo snad automaticky aktualizovat. Z persons.json jsem se snažil vymáčknout co nejvíc, takže máme informace o nakažených v jednotlivých krajích v tabulce, nakažených podle věkových skupin a importovaní nakažení podle země. Časy do current_numbers_uzis.json beru přímo z HTML webové stránky onemocnění aktuálně.
